FROM quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:jdk-21@sha256:fc5c7970ce45c0d07a70ab3955fa72af79a2be65a7a89e0a29e0ab785a1dda74 AS build
COPY --chown=quarkus:quarkus mvnw /code/mvnw
COPY --chown=quarkus:quarkus .mvn /code/.mvn
COPY --chown=quarkus:quarkus pom.xml /code/
USER quarkus
WORKDIR /code
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline
COPY src /code/src
# ARG QUARKUS_PROFILE
# ARG APP_NAME
RUN ./mvnw package -Pnative -Dquarkus.application.name=atm-layer-schema -Dquarkus.profile=prod

## Stage 2 : create the docker final image
FROM quay.io/quarkus/quarkus-micro-image:2.0@sha256:38c75e7b4f5b2a60da4300d7d0c2751e8df806e816d1b434b07e8bbd62cfe8d0
WORKDIR /work/
COPY --from=build /code/target/*-runner /work/application

# set up permissions for user `1001`
RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
