FROM quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:jdk-21@sha256:57df330f971a475941a035bbe6c0aef0bc75d5a9f1eba7ae6eaeac9741afd8f1 AS build
COPY --chown=quarkus:quarkus mvnw /code/mvnw
COPY --chown=quarkus:quarkus .mvn /code/.mvn
COPY --chown=quarkus:quarkus pom.xml /code/
USER quarkus
WORKDIR /code
RUN ./mvnw -B org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline
COPY src /code/src
# ARG QUARKUS_PROFILE
# ARG APP_NAME
RUN ./mvnw package -Pnative -Dquarkus.application.name=atm-layer-schema -Dquarkus.profile=prod

## Stage 2 : create the docker final image
FROM quay.io/quarkus/quarkus-micro-image:2.0@sha256:08263c65b8fc93055cd1ac62e6d63eeb612270f0e37a03bd1ab7a69b3e272a7b
WORKDIR /work/
COPY --from=build /code/target/*-runner /work/application

# set up permissions for user `1001`
RUN chmod 775 /work /work/application \
  && chown -R 1001 /work \
  && chmod -R "g+rwX" /work \
  && chown -R 1001:root /work

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
